"""
Validation testing for the Devon Air Ambulance Discrete Event Simulation (DES) Model.

These check that the results generated by the model when fed with 'current' parameters are within
acceptable range that sufficiently mirrors real world.

Unlike some other testing, we wouldn't expect perfect matches here due to inherent variability.
Therefore, functions like pytest.approx() will be used for testing values fall within a reasonable
margin of the real-world figures.

Planned tests are listed below with a [].
Implemented tests are listed below with a [x].

## Arrivals

[] Total number of calls over period
[] Pattern of calls across the course of a day
[] Pattern of calls across seasons
[] Split of calls across AMPDS cards

## Response Times

[] Distribution of response times

## Utilisation

[] Total utilisation
[] Utilisation split across different resources
[] Utilisation at different times of day
[] Utlisation across seasons

"""
